default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: gemblocker_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: gemblocker_test

production:
  <<: *default
  database: gemblocker_production