# # # # # # # # # # # # # # # # # # # #
# GitLab Web Service config file      #
# Put the WS URL for each environment #
# # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # Example # # # # # # # # # # # #
# development:                                    #
#   base_ws_url: "https://mydomain.com/api/v3/"    #
#   projects_path: "projects"                     #
#   private_token: "892021AISjAS"                 #
# # # # # # # # # # # # # # # # # # # # # # # # # #


development:
  base_ws_url: "YOUR_BASE_WS_URL_HERE"
  projects_path: "projects"
  private_token: "YOUR_PRIVATE_TOKEN"

test:
  base_ws_url: "YOUR_BASE_WS_URL_HERE"
  projects_path: "projects"
  private_token: "YOUR_PRIVATE_TOKEN"

staging:
  base_ws_url: "YOUR_BASE_WS_URL_HERE"
  projects_path: "projects"
  private_token: "YOUR_PRIVATE_TOKEN"

production:
  base_ws_url: "YOUR_BASE_WS_URL_HERE"
  projects_path: "projects"
  private_token: "YOUR_PRIVATE_TOKEN"
